import { getDocument,GlobalWorkerOptions,type PDFDocumentLoadingTask } from "pdfjs-dist";import workerUrl from "pdfjs-dist/build/pdf.worker.min.mjs?url";
import { DocumentTypeDetector,type DocumentType } from "./DocumentTypeDetector";import { PaginationEngine,type PaginationMetrics } from "./PaginationEngine";import { PdfTextExtractor } from "./PdfTextExtractor";import { TextLayoutEngine } from "./TextLayoutEngine";import type { ReaderDocument,ReaderPage,ReadingAnchor } from "./ReaderDocument";
GlobalWorkerOptions.workerSrc=workerUrl;
export class ReflowReaderEngine {private task:PDFDocumentLoadingTask|null=null;private document:ReaderDocument|null=null;private pages:ReaderPage[]=[];private index=0;private anchor:ReadingAnchor={paragraphId:"p-0",textOffset:0,logicalOffset:0};
  private cover:{title:string;author?:string;image?:string}|null=null;
  private coverVisible=false;
  public async open(blob:Blob,metrics:PaginationMetrics,logicalOffset=0,cover?:{title:string;author?:string;image?:string},openAtCover=true):Promise<DocumentType>{this.cover=cover??null;this.coverVisible=Boolean(this.cover)&&openAtCover;this.task=getDocument({data:await blob.arrayBuffer()});const pdf=await this.task.promise;const type=await new DocumentTypeDetector().detect(pdf);if(type!=="IMAGE_BASED"){this.document=new TextLayoutEngine().layout(await new PdfTextExtractor().extract(pdf));this.anchor={paragraphId:"p-0",textOffset:0,logicalOffset};this.repaginate(metrics);}return type;}
  public repaginate(metrics:PaginationMetrics):void{if(!this.document)return;const engine=new PaginationEngine(),content=engine.paginate(this.document,metrics);this.pages=this.cover?engine.withCover(content,this.cover):content;this.index=this.coverVisible&&this.cover?0:engine.pageForAnchor(this.pages,this.anchor);}
  public next():boolean{if(this.index>=this.pages.length-1)return false;this.index++;this.updateAnchor();return true;}public previous():boolean{if(this.index<=0)return false;this.index--;this.updateAnchor();return true;}public goTo(page:number):void{if(page<1||page>this.pages.length)throw new Error(`Escolha uma página entre 1 e ${this.pages.length}.`);this.index=page-1;this.updateAnchor();}
  public get currentPage():ReaderPage{return this.pages[this.index]!;}public get currentPageNumber():number{return this.index+1;}public get totalPages():number{return this.pages.length;}public get readingAnchor():ReadingAnchor{return this.anchor;}public window():ReaderPage[]{return this.pages.slice(Math.max(0,this.index-1),this.index+2);}public async close():Promise<void>{await this.task?.destroy();this.task=null;}
  public pageAt(pageNumber:number):ReaderPage|null{return this.pages[pageNumber-1]??null;}
  public get allPages():readonly ReaderPage[]{return this.pages;}
  private updateAnchor():void{const page=this.currentPage;this.coverVisible=Boolean(page.cover);if(page.cover)return;this.anchor={paragraphId:page.paragraphs[0]?.id??"p-0",textOffset:0,logicalOffset:page.startOffset};}
}
