import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { BookFocusTransformAudit } from "../src/components/BookFocusTransformAudit";
import { describe, it } from "node:test";
import { BookSelectionController } from "../src/components/BookSelectionController";
import { BookPerspectiveLayout } from "../src/components/BookPerspectiveLayout";
import { BookSpineRenderer } from "../src/components/BookSpineRenderer";
import { Book3DShell } from "../src/components/Book3DShell";
import { BookSpineColorService, BookSpinePaletteService } from "../src/components/BookSpineColorService";
import { BookVolumeFormatter } from "../src/components/BookVolumeFormatter";
import { AuthorShelfGroup } from "../src/components/AuthorShelfGroup";
import { ShelfBoard, ShelfBottomShadow, ShelfEdgeHighlight, ShelfFrontFace, ShelfTopFace } from "../src/components/ShelfBoard";
import { BookFocusAnimator } from "../src/components/BookFocusAnimator";
import { BookDisplayModeResolver } from "../src/components/BookDisplayModeResolver";
import { BookShelfCompactionLayout } from "../src/components/BookShelfCompactionLayout";
import { Book3D } from "../src/components/Book3D";
import { Book3DFactory } from "../src/components/Book3DFactory";
import { BookBottomFace, BookDepthFace, BookSpineBevel, BookWoodShadow, BookFrontFace, BookPageBlock, BookShadowLayer, BookSpineFace, BookTopFace, PageBlock3D, PageFrontInset, PageInset, PageSideFace, PageTopFace, TopCoverFace } from "../src/components/Book3DFaces";
import { ShelfFocusLabel } from "../src/components/ShelfFocusLabel";
import { Book3DGeometry } from "../src/components/Book3DGeometry";
import { BookSeriesResolver } from "../src/components/BookSeriesResolver";
import { BookContextLabelResolver } from "../src/components/BookContextLabelResolver";
import { BookQuickPreview } from "../src/components/BookQuickPreview";
import { BookShelf } from "../src/components/BookShelf";
import { BookShelfCard3D } from "../src/components/BookShelfCard3D";
import { BookInteractionRegion } from "../src/components/BookInteractionRegion";
import { GenreShelf } from "../src/components/GenreShelf";
import { Book } from "../src/models/Book";
import { Genre } from "../src/models/Genre";
import { Library } from "../src/models/Library";

const book = (id: string, genreId: string) => new Book({ id, title: `Livro ${id}`, author: "Autor", genreId, cover: "capa",
  fileType: "pdf", fileName: `${id}.pdf`, fileSize: 10, mimeType: "application/pdf", readingStatus: "unread" });

describe("BookSelectionController", () => {
  it("selectFirstBook", () => { const controller = new BookSelectionController(); assert.equal(controller.activate("a"), "selected"); assert.equal(controller.isSelected("a"), true); });
  it("selectAnotherBook e deselectPrevious", () => { const controller = new BookSelectionController(); controller.select("a"); assert.equal(controller.select("b"), "a"); assert.equal(controller.isSelected("a"), false); assert.equal(controller.isSelected("b"), true); });
  it("secondTapActivates", () => { const controller = new BookSelectionController(); controller.activate("a"); assert.equal(controller.activate("a"), "activated"); });
  it("deselect", () => { const controller = new BookSelectionController(); controller.select("a"); assert.equal(controller.deselect(), "a"); assert.equal(controller.isSelected("a"), false); });
  it("onlyOneFinalFocusedBook e previousReturnsWhenNextFocuses",()=>{const controller=new BookSelectionController();controller.select("a");controller.settle("a");controller.select("b");assert.equal(controller.state("a"),"RETURNING");assert.equal(controller.state("b"),"FOCUSING");controller.settle("a");controller.settle("b");assert.equal(controller.state("a"),"RESTING");assert.equal(controller.state("b"),"FOCUSED");});
  it("rapidFocusSwitchDoesNotCorruptState",()=>{const controller=new BookSelectionController();["a","b","c","a"].forEach(id=>controller.select(id));controller.settle("a");assert.equal(controller.state("a"),"FOCUSED");assert.notEqual(controller.state("c"),"FOCUSED");});
  it("animationsCanOverlapDuringSwitch",()=>assert.equal(BookFocusAnimator.canOverlap,true));
});

describe("BookShelf", () => {
  it("compacta progressivamente sem ocultar livros", () => { assert.ok(BookShelf.compactionFor(20) < BookShelf.compactionFor(4)); assert.ok(BookShelf.compactionFor(20) > -8); });
  it("swipeDoesNotActivate", () => { assert.equal(BookShelf.isTap(18, 2), false); assert.equal(BookShelf.isTap(4, 3), true); });
  it("um livro permanece físico, inclinado e com lombada", () => { const profile = BookShelf.visualProfile(1); assert.equal(profile.frontal, false); assert.equal(profile.angle,81); });
  it("toda estante solicita spine e perspectiva",()=>{assert.equal(BookPerspectiveLayout.forCount(1).mode,"ANGLED_SOFT");assert.equal(BookPerspectiveLayout.forCount(2).mode,"ANGLED_SOFT");assert.equal(Book3DShell.hasSpine("ANGLED_SOFT"),true);assert.equal(Book3DShell.hasTop("ANGLED_SOFT"),true);assert.equal(Book3DShell.hasSpine("ANGLED"),true);});
  it("dois livros recebem inclinação forte e três recebem inclinação evidente", () => { assert.equal(BookShelf.visualProfile(2).mode,"ANGLED_SOFT");const profile = BookShelf.visualProfile(3); assert.equal(profile.frontal, false); assert.equal(profile.angle,81); });
  it("quatro ou mais livros mantêm geometria robusta e posições fixas", () => { const medium = BookShelf.visualProfile(4); const many = BookShelf.visualProfile(12); assert.equal(medium.mode,"ANGLED_REFERENCE");assert.equal(medium.angle,81);assert.equal(many.angle,medium.angle);assert.ok(many.overlap<0); });
  it("gap permanece mínimo e consistente", () => { [1,3,5,8,20].forEach(count=>assert.equal(BookShelf.visualProfile(count).gap,2)); });
  it("foco preserva ângulo em múltiplos livros",()=>assert.notEqual(BookPerspectiveLayout.forCount(4).selectedAngle,0));
  it("responsividade reduz livros no mobile",()=>assert.ok(BookPerspectiveLayout.responsiveWidth(390)<BookPerspectiveLayout.responsiveWidth(1280)));
  it("texto e fallback da lombada",()=>{const value=book("a","g");assert.deepEqual(BookSpineRenderer.text(value),["Livro a","Autor"]);assert.notEqual(BookSpineRenderer.fallbackColor("pdf"),BookSpineRenderer.fallbackColor("epub"));});
  it("focusedModeKeepsAngle",()=>assert.equal(Book3DShell.focus("ANGLED"),"FOCUSED_ANGLED"));
  it("spineUsesDerivedColor",()=>assert.equal(new BookSpineColorService().fromPixels([100,50,200,255]),"rgb(68, 34, 136)"));
  it("volumeDisplayedWhenPresent e volumeHiddenWhenAbsent",()=>{const formatter=new BookVolumeFormatter();assert.equal(formatter.format("1"),"Vol. 1");assert.equal(formatter.format(),null);});
  it("shelfBoardIndependentFromTrack e booksTrackScrolls",()=>{assert.equal(ShelfBoard.independentFromTrack,true);assert.equal(BookShelf.trackScrolls,true);});
  it("authorGroupCreatedForMultipleBooks",()=>{const result=new AuthorShelfGroup().group([book("a","g"),book("b","g")]);assert.equal(result.groups[0]?.author,"Autor");assert.equal(result.ungrouped.length,0);});
  it("singleAuthorBookDoesNotForceGroup",()=>{const result=new AuthorShelfGroup().group([book("a","g")]);assert.equal(result.groups.length,0);assert.equal(result.ungrouped.length,1);});
  it("volumesSortedNumerically",()=>{const values=[new Book({...book("10","g"),volume:"10"}),new Book({...book("2","g"),volume:"2"}),new Book({...book("1","g"),volume:"1"})];assert.deepEqual(new AuthorShelfGroup().sortVolumes(values).map(value=>value.volume),["1","2","10"]);});
  it("spineTextRotatedAsUnit",()=>assert.equal(BookSpineRenderer.textOrientation,"ROTATED_UNIT"));
  it("angledModeUsesPerspective",()=>assert.equal(BookPerspectiveLayout.forCount(5).angle,81));
  it("genericShelfShowsTitleAndAuthor",()=>assert.deepEqual(new BookContextLabelResolver().resolve(book("a","g"),{kind:"genre",label:"Ação"}),{title:"Livro a",subtitle:"Autor"}));
  it("authorShelfHidesRepeatedAuthor",()=>assert.deepEqual(new BookContextLabelResolver().resolve(book("a","g"),{kind:"author",label:"Obras de Autor"}),{title:"Livro a",subtitle:undefined}));
  it("volumeDisplayedCorrectly",()=>{const value=new Book({...book("a","g"),volume:"2"});assert.equal(new BookContextLabelResolver().resolve(value,{kind:"genre",label:"Ação"}).title,"Livro a · Vol. 2");});
  it("quickPreviewUsesRealMetadata e missingSummaryDoesNotGenerateFakeSummary",()=>{assert.equal(BookQuickPreview.summary(new Book({...book("a","g"),summary:"Resumo real"})),"Resumo real");assert.equal(BookQuickPreview.summary(book("a","g")),"Resumo não disponível.");});
  it("focusedStateKeepsAngle",()=>assert.notEqual(BookFocusAnimator.angleFor("FOCUSED",-20,-12),0));
  it("focusedStateKeepsSpine",()=>assert.equal(BookFocusAnimator.keepsSpine("FOCUSED"),true));
  it("focusedTransformDoesNotResetRotation",()=>assert.equal(BookFocusAnimator.angleFor("FOCUSING",-20,-12),-12));
  it("returningStateKeepsAngle",()=>assert.equal(BookFocusAnimator.angleFor("RETURNING",-20,-12),-20));
  it("switchingBooksPreserves3D",()=>{const controller=new BookSelectionController();controller.select("a");controller.settle("a");controller.select("b");assert.equal(BookFocusAnimator.keepsSpine(controller.state("a")),true);assert.notEqual(BookFocusAnimator.angleFor(controller.state("b"),-20,-12),0);});
  it("displayModeUsesRenderedShelfCount",()=>assert.equal(new BookDisplayModeResolver().resolve({renderedShelfBookCount:4,viewport:{width:437,kind:"mobile"},focusState:"RESTING"}),"ANGLED_REFERENCE"));
  it("singleBookShelfUsesPhysicalAngle",()=>assert.equal(new BookDisplayModeResolver().resolve({renderedShelfBookCount:1}),"ANGLED_SOFT"));
  it("twoBookShelfUsesSoftAngle",()=>assert.equal(new BookDisplayModeResolver().resolve({renderedShelfBookCount:2}),"ANGLED_SOFT"));
  it("threeBookShelfForcesAngled",()=>assert.equal(new BookDisplayModeResolver().resolve({renderedShelfBookCount:3}),"ANGLED_REFERENCE"));
  it("fourBookShelfForcesAngled",()=>assert.equal(new BookDisplayModeResolver().resolve({renderedShelfBookCount:4}),"ANGLED_REFERENCE"));
  it("authorSubgroupCountDrivesDisplayMode",()=>{const group=new AuthorShelfGroup().group([book("a","g"),book("b","g"),book("c","g"),book("d","g")]).groups[0];assert.equal(new BookDisplayModeResolver().resolve({renderedShelfBookCount:group?.books.length??0}),"ANGLED_REFERENCE");});
  it("focusedBookKeepsAngleInThreePlusShelf",()=>{const profile=BookShelf.visualProfile(3);assert.equal(profile.selectedAngle,81);});
  it("frontModeBlockedWhenShelfCountIsThreeOrMore",()=>[3,4,12].forEach(count=>assert.notEqual(new BookDisplayModeResolver().resolve({renderedShelfBookCount:count}),"FRONT")));
  it("angledModeProducesVisibleSpine",()=>assert.equal(new BookDisplayModeResolver().allowsSpine({renderedShelfBookCount:3}),true));
  it("singleBookUsesAngled3D",()=>assert.equal(BookShelf.visualProfile(1).mode,"ANGLED_SOFT"));
  it("twoBooksUseSoftAngle",()=>assert.equal(BookShelf.visualProfile(2).mode,"ANGLED_SOFT"));
  it("threeBooksUseAngledReference",()=>assert.equal(BookShelf.visualProfile(3).mode,"ANGLED_REFERENCE"));
  it("fourBooksUseAngledReference",()=>assert.equal(BookShelf.visualProfile(4).mode,"ANGLED_REFERENCE"));
  it("angledReferenceShowsVisibleSpine",()=>assert.equal(Book3DShell.hasSpine("ANGLED"),true));
  it("focusedBookKeepsDiagonalInThreePlus",()=>assert.equal(BookFocusAnimator.angleFor("FOCUSED",BookShelf.visualProfile(4).angle,BookShelf.visualProfile(4).selectedAngle),81));
  it("firstClickFocusesAndPullsBookForward",()=>{const controller=new BookSelectionController();assert.equal(controller.activate("a"),"selected");assert.equal(controller.state("a"),"FOCUSING");});
  it("secondClickOpensReader",()=>{const controller=new BookSelectionController();controller.activate("a");assert.equal(controller.activate("a"),"activated");});
  it("switchFocusReturnsPreviousAndAdvancesNext",()=>{const controller=new BookSelectionController();controller.select("a");controller.settle("a");controller.select("b");assert.equal(controller.state("a"),"RETURNING");assert.equal(controller.state("b"),"FOCUSING");});
  it("threePlusBooksUseControlledOverlap",()=>{const layout=new BookShelfCompactionLayout();assert.equal(layout.resolve(3,1440).visibleCoverRatio,.4);assert.equal(layout.resolve(4,1440).overlapRatio,.6);});
  it("compactOverlapIsResponsive",()=>{const layout=new BookShelfCompactionLayout();assert.equal(layout.resolve(4,437).visibleCoverRatio,.34);assert.equal(layout.resolve(4,768).visibleCoverRatio,.37);assert.equal(layout.resolve(4,1440).visibleCoverRatio,.4);});
  it("compactLayoutKeepsPartialCoverWithinLimit",()=>{const layout=new BookShelfCompactionLayout();[437,768,1440].forEach(width=>{const ratio=layout.resolve(4,width).visibleCoverRatio;assert.ok(ratio>=.2&&ratio<=.45);});});
  it("singleAndTwoBookShelvesRemainPhysical",()=>{const layout=new BookShelfCompactionLayout();assert.equal(layout.resolve(1,437).visibleCoverRatio,.42);assert.ok(layout.resolve(2,1440).overlapRatio>0);});
  it("focusDoesNotReflowCompactShelf",()=>assert.equal(BookShelfCompactionLayout.keepsPositionWhileFocused,true));
  it("book3DHasIndependentFrontFace",()=>assert.notEqual(BookFrontFace,BookSpineFace));
  it("book3DHasIndependentSpineFace",()=>assert.notEqual(BookSpineFace,BookDepthFace));
  it("book3DHasTopFace",()=>assert.notEqual(BookTopFace,BookPageBlock));
  it("book3DUsesPreserve3D",()=>assert.equal(Book3D.usesPreserve3D,true));
  it("threePlusUsesBook3DAngled",()=>assert.equal(BookShelf.visualProfile(3).mode,"ANGLED_REFERENCE"));
  it("book3DFactoryBuildsFromMetadata",()=>{const value=new Book({...book("a","g"),volume:"2",series:"Série"});const model=new Book3DFactory().model(value,"ANGLED");assert.deepEqual({id:model.bookId,title:model.title,author:model.author,volume:model.volume,series:model.series},{id:"a",title:"Livro a",author:"Autor",volume:"2",series:"Série"});});
  it("focusedBookKeeps3DGeometry",()=>assert.equal(BookFocusAnimator.keepsSpine("FOCUSED"),true));
  it("focoDeslizaSemGirarNemCrescer",()=>{assert.equal(BookFocusAnimator.rigidTranslationOnly,true);assert.equal(BookFocusAnimator.lateralDriftComesFromPerspective,true);assert.equal(BookFocusAnimator.scaleFor("FOCUSED"),BookFocusAnimator.scaleFor("RESTING"));assert.equal(BookFocusAnimator.tiltFor("FOCUSED"),0);assert.ok(BookFocusAnimator.lateralFor("FOCUSED","desktop")<0);assert.ok(Math.abs(BookFocusAnimator.lateralFor("FOCUSED","desktop"))<=BookShelfCompactionLayout.focusLateralStepPixels+3);assert.ok(BookFocusAnimator.verticalFor("FOCUSED","desktop")>0);assert.equal(BookFocusAnimator.depthFor("FOCUSED","desktop"),BookFocusAnimator.depthFor("RESTING","desktop"));});
  it("firstClickDoesNotOpen",()=>{const controller=new BookSelectionController();assert.equal(controller.activate("a"),"selected");});
  it("secondClickOpens",()=>{const controller=new BookSelectionController();controller.activate("a");assert.equal(controller.activate("a"),"activated");});
  it("focusedBookDoesNotFlatten",()=>assert.notEqual(BookFocusAnimator.angleFor("FOCUSED",-20,-13),0));
  it("book3DUsesReferenceGeometry",()=>{const profile=BookShelf.visualProfile(5);assert.equal(profile.angle,81);assert.equal(profile.selectedAngle,81);});
  it("spineIsVisibleOnLeft",()=>assert.equal(Book3DShell.hasSpine("ANGLED"),true));
  it("frontFaceRemainsPartiallyVisible",()=>{const ratio=new BookShelfCompactionLayout().resolve(5,1440).visibleCoverRatio;assert.ok(ratio>=.2&&ratio<=.45);});
  it("topFaceVisibleInAngledMode",()=>assert.equal(Book3DShell.hasTop("ANGLED"),true));
  it("booksUseControlledVisualOverlap",()=>assert.equal(new BookShelfCompactionLayout().resolve(5,1440).overlapRatio,.6));
  it("focusDoesNotRelayoutTrack",()=>assert.equal(BookShelfCompactionLayout.keepsPositionWhileFocused,true));
  it("focusKeepsRotation",()=>{const profile=BookShelf.visualProfile(5);assert.equal(profile.angle,profile.selectedAngle);});
  it("returnUsesInverseGeometry",()=>assert.equal(BookFocusAnimator.returnUsesSamePath,true));
  it("switchFocusAnimatesBoth",()=>assert.equal(BookFocusAnimator.canOverlap,true));
  it("neighborsRemainStationary",()=>assert.equal(BookFocusAnimator.neighborsRemainStationary,true));
  it("bookIsPhysical3D",()=>assert.equal(Book3D.isPhysicalBook,true));
  it("bookKeepsAngleDuringFocus",()=>{const profile=BookShelf.visualProfile(5);assert.equal(profile.angle,profile.selectedAngle);});
  it("bookHasIndependentContactShadow",()=>assert.equal(BookShadowLayer.independentContactShadow,true));
  it("focusDoesNotMoveNeighbors",()=>assert.equal(BookFocusAnimator.neighborsRemainStationary,true));
  it("returnUsesExactInversePath",()=>assert.equal(BookFocusAnimator.returnUsesSamePath,true));
  it("clickShelfBackgroundClearsFocus",()=>assert.equal(BookShelf.backgroundClickClearsFocus,true));
  it("focusLabelAlwaysCentered",()=>assert.equal(ShelfFocusLabel.alwaysCentered,true));
  it("carouselHasEdgePadding",()=>assert.equal(BookShelfCompactionLayout.edgePaddingPixels,10));
  it("carouselSnapsAfterScroll",()=>assert.equal(BookShelfCompactionLayout.carouselSnapsAfterScroll,true));
  it("dragDoesNotSelectBook",()=>assert.equal(BookShelf.isTap(11,0),false));
  it("scrollClearsFocusedBook",()=>assert.equal(BookShelf.scrollClearsFocusedBook,true));
  it("shelfBoardDoesNotScroll",()=>assert.equal(ShelfBoard.independentFromTrack,true));
  it("bookHasTrue3DGeometry",()=>assert.equal(Book3DGeometry.trueThreeDimensionalGeometry,true));
  it("spineFaceHasPhysicalWidth",()=>{const geometry=new Book3DGeometry(11,16.5,1.35,1.35,.08,.16);assert.ok(geometry.spineRatio>=.1&&geometry.spineRatio<=.16);});
  it("topFaceIsVisible",()=>assert.equal(BookTopFace.visibleInAngledMode,true));
  it("bookUsesPreserve3D",()=>assert.equal(Book3D.usesPreserve3D,true));
  it("bookKeepsSameRotateYWhenFocused",()=>{const profile=BookShelf.visualProfile(5);assert.equal(profile.angle,profile.selectedAngle);});
  it("focusUsesTranslateZ",()=>assert.equal(BookFocusAnimator.focusUsesTranslateZ,true));
  it("focusDoesNotRelayoutNeighbors",()=>assert.equal(BookFocusAnimator.neighborsRemainStationary,true));
  it("contactShadowStaysOnShelfPlane",()=>assert.equal(BookShadowLayer.staysOnShelfPlane,true));
  it("returnUsesInverseTransform",()=>assert.equal(BookFocusAnimator.returnUsesSamePath,true));
  it("focusUsesCompoundDiagonalTrajectory",()=>assert.equal(BookFocusAnimator.focusUsesCompoundTrajectory,true));
  it("focusedBookMovesStraightForward",()=>{(["mobile","tablet","desktop"] as const).forEach(v=>{const x=BookFocusAnimator.lateralFor("FOCUSED",v);assert.ok(x<0);assert.ok(Math.abs(x)<=BookShelfCompactionLayout.focusLateralStepPixels+3);assert.ok(BookFocusAnimator.verticalFor("FOCUSED",v)>0);assert.equal(BookFocusAnimator.depthFor("FOCUSED",v),BookFocusAnimator.depthFor("RESTING",v));});assert.equal(BookFocusAnimator.scaleFor("FOCUSED"),BookFocusAnimator.scaleFor("RESTING"));assert.equal(BookFocusAnimator.tiltFor("FOCUSED"),0);});
  it("restingAndReturningHaveNoLateralOffset",()=>{assert.equal(BookFocusAnimator.lateralFor("RESTING"),0);assert.equal(BookFocusAnimator.lateralFor("RETURNING"),0);});
  it("trajetoriaMudaEmYeXsemMudarZ",()=>{for(const viewport of ["mobile","tablet","desktop"] as const){const end=BookFocusAnimator.trajectoryAt(1,viewport),start=BookFocusAnimator.trajectoryAt(0,viewport);assert.equal(end.y,BookFocusAnimator.vectorFor(viewport).y);assert.equal(start.y,0);assert.equal(end.z,start.z);assert.ok(end.x<0);assert.equal(start.x,0);assert.ok(end.y>0);}});
  it("seriesAndCollectionsAreDetected",()=>{const resolver=new BookSeriesResolver(),a=new Book({...book("a","g"),title:"Obra Vol. 1"}),b=new Book({...book("b","g"),title:"Obra Vol. 2"});assert.equal(resolver.sameSeries(a,b),true);assert.equal(resolver.resolve(b).volume,2);assert.equal(resolver.resolve(b).baseTitle,"Obra");});
  it("seriesVolumesAreSortedNumerically",()=>{const values=[3,1,2].map(volume=>new Book({...book(String(volume),"g"),title:`Obra Parte ${volume}`}));assert.deepEqual(new BookSeriesResolver().order(values).map(value=>value.title),["Obra Parte 1","Obra Parte 2","Obra Parte 3"]);});
  it("unrelatedBooksKeepNaturalOrder",()=>{const values=[new Book({...book("b","g"),title:"Zeta"}),new Book({...book("a","g"),title:"Alfa"})];assert.deepEqual(new BookSeriesResolver().order(values).map(value=>value.title),["Zeta","Alfa"]);});
  it("authorShelfCanOmitRepeatedSpineAuthor",()=>assert.equal(new Book3DFactory().model(book("a","g"),"ANGLED",false).showAuthor,false));
  it("spineAndDepthAreThicker",()=>{const model=new Book3DFactory().model(book("a","g"),"ANGLED");assert.equal(model.dimensions.spineRem,4.2);assert.equal(model.dimensions.depthRem,4.2);});
  it("hardCoverIsSeparatedFromPageBlock",()=>{const geometry=Book3DGeometry.from(new Book3DFactory().model(book("a","g"),"ANGLED"));assert.equal(geometry.coverThickness,.25);assert.equal(geometry.pageInset*16,3);assert.equal(geometry.pageBlockDepth,3.7);});
  it("shelfHasPhysicalTopFace",()=>assert.equal(ShelfBoard.hasPhysicalTopFace,true));
  it("shelfHasPhysicalFrontFace",()=>assert.equal(ShelfBoard.hasPhysicalFrontFace,true));
  it("shelfHasThickness",()=>assert.ok(ShelfBoard.thicknessRem>=1.25));
  it("bookTouchesShelfSurface",()=>assert.equal(BookShadowLayer.staysOnShelfPlane,true));
  it("bookHasContactShadow",()=>assert.equal(BookShadowLayer.independentContactShadow,true));
  it("focusPreservesBookGeometry",()=>assert.equal(Book3D.isPhysicalBook,true));
  it("focusPreservesBookAngle",()=>{const profile=BookShelf.visualProfile(5);assert.equal(profile.angle,profile.selectedAngle);});
  it("focusMovesOnlySelectedBook",()=>assert.equal(BookFocusAnimator.neighborsRemainStationary,true));
  it("focusLightensBookGradually",()=>assert.equal(BookFocusAnimator.lightensGradually,true));
  it("focusExpandsShadow",()=>assert.equal(BookFocusAnimator.shadowExpandsWithFocus,true));
  it("returnUsesInverseTrajectory",()=>assert.equal(BookFocusAnimator.returnUsesSamePath,true));
  it("returnReversesShadow",()=>assert.equal(BookFocusAnimator.shadowReturnUsesSamePath,true));
  it("clickShelfClearsFocus",()=>assert.equal(BookShelf.backgroundClickClearsFocus,true));
  it("passoLateralPequenoNoFoco",()=>["mobile","tablet","desktop"].forEach(viewport=>{const x=BookFocusAnimator.vectorFor(viewport as "mobile"|"tablet"|"desktop").x;assert.ok(x<0);assert.ok(Math.abs(x)<=BookShelfCompactionLayout.focusLateralStepPixels+3);}));
  it("focusedBookMovesForward",()=>["mobile","tablet","desktop"].forEach(viewport=>{assert.equal(BookFocusAnimator.vectorFor(viewport as "mobile"|"tablet"|"desktop").z,0);assert.ok(BookFocusAnimator.vectorFor(viewport as "mobile"|"tablet"|"desktop").y>0);}));
  it("focusedBookNeverMovesRight",()=>[0,.2,.4,.6,.8,1].forEach(progress=>assert.ok(BookFocusAnimator.trajectoryAt(progress).x<=0)));
  it("extracaoDeslizaEmYeXsemMudarZ",()=>[.2,.4,.6,.8,1].forEach(progress=>{const point=BookFocusAnimator.trajectoryAt(progress),rest=BookFocusAnimator.trajectoryAt(0);assert.ok(point.x<rest.x);assert.equal(point.z,rest.z);assert.ok(point.y>rest.y);assert.equal(BookFocusAnimator.growthAt(progress),BookFocusAnimator.growthAt(0));}));
  it("focoNaoTrocaDeCamadaNoMeioDaExtracao",()=>{assert.equal(BookFocusAnimator.focusedStackingIsPinned,true);assert.equal(BookFocusAnimator.stackingChangesAfterExtractionStarts,false);[.05,.2,.4,.7,1].forEach(p=>assert.equal(BookFocusAnimator.stackLayerAt(p),40));});
  it("extractionUsesPhysicalDurationAndEasing",()=>{assert.equal(new BookFocusAnimator().duration,800);assert.equal(BookFocusAnimator.easing,"cubic-bezier(.20,.72,.18,1)");});
  it("pageTopIsSolidBlock",()=>assert.equal(PageTopFace.isSolidBlock,true));
  it("pageTopDoesNotLookLikeLooseSheet",()=>assert.equal(PageTopFace.hasLiftedCorners,false));
  it("pageBlockRemainsInsideCovers",()=>{assert.equal(PageTopFace.remainsInsideCovers,true);assert.ok(TopCoverFace.overhangPixels>=1&&TopCoverFace.overhangPixels<=3);});
  it("pageTopKeepsGeometryDuringFocus",()=>assert.equal(PageTopFace.preservesGeometryDuringFocus,true));
  it("spineIsThicker",()=>assert.ok(Book3DGeometry.from(new Book3DFactory().model(book("a","g"),"ANGLED")).spineWidth>2.7));
  it("bookDepthIsGreater",()=>assert.ok(Book3DGeometry.from(new Book3DFactory().model(book("a","g"),"ANGLED")).depth>3));
  it("coverThicknessIsGreater",()=>assert.ok(Book3DGeometry.from(new Book3DFactory().model(book("a","g"),"ANGLED")).coverThickness>.16));
  it("pageBlockDepthMatchesBookDepth",()=>{const geometry=Book3DGeometry.from(new Book3DFactory().model(book("a","g"),"ANGLED"));assert.equal(geometry.pageBlockDepth,geometry.depth-geometry.coverThickness*2);});
  it("bookStillFormsClosed3DVolume",()=>assert.equal(Book3DGeometry.from(new Book3DFactory().model(book("a","g"),"ANGLED")).formsClosedVolume,true));
  it("firstBookHasStartPadding",()=>assert.equal(BookShelfCompactionLayout.startPaddingPixels,10));
  it("lastBookHasEndPadding",()=>assert.equal(BookShelfCompactionLayout.endPaddingPixels,10));
  it("middleScrollCanClipAtEdges",()=>assert.equal(BookShelfCompactionLayout.middleScrollCanClipAtEdges,true));
  it("firstSnapKeepsStartPadding",()=>{assert.equal(BookShelfCompactionLayout.snapType,"x proximity");assert.equal(BookShelfCompactionLayout.snapAlign,"start");});
  it("lastSnapKeepsEndPadding",()=>assert.equal(BookShelfCompactionLayout.endPaddingPixels,BookShelfCompactionLayout.edgePaddingPixels));
  it("carouselDoesNotResizeBooks",()=>assert.equal(BookShelfCompactionLayout.preservesBookDimensions,true));
  it("bookHasNoVerticalTilt",()=>{assert.equal(BookPerspectiveLayout.rotateX,0);assert.equal(BookPerspectiveLayout.rotateZ,0);});
  it("bookRotateXIsZero",()=>assert.equal(BookPerspectiveLayout.rotateX,0));
  it("bookRotateZIsZero",()=>assert.equal(BookPerspectiveLayout.rotateZ,0));
  it("bookKeepsReferenceHorizontalYaw",()=>assert.ok(BookPerspectiveLayout.rotateY>=79&&BookPerspectiveLayout.rotateY<=83));
  it("bookSpineIsThicker",()=>assert.ok(new Book3DFactory().model(book("a","g"),"ANGLED").dimensions.spineRem>3.1));
  it("bookDepthIsThicker",()=>assert.ok(new Book3DFactory().model(book("a","g"),"ANGLED").dimensions.depthRem>3.4));
  it("focusedBookIsInFrontOfShelfFrontFace",()=>assert.equal(BookFocusAnimator.focusedBookIsInFrontOfShelf,true));
  it("focusedBookDoesNotClipBehindBoard",()=>assert.equal(ShelfBoard.doesNotClipFocusedBook,true));
  it("focusedBookMovesFartherForward",()=>{assert.deepEqual([BookFocusAnimator.vectorFor("mobile").y,BookFocusAnimator.vectorFor("tablet").y,BookFocusAnimator.vectorFor("desktop").y],[38,38,38]);assert.deepEqual([BookFocusAnimator.vectorFor("mobile").z,BookFocusAnimator.vectorFor("tablet").z,BookFocusAnimator.vectorFor("desktop").z],[0,0,0]);});
  it("contactShadowRemainsOnShelfTop",()=>assert.equal(BookShadowLayer.remainsOnShelfTopDuringFocus,true));
  it("shelfDoesNotMoveDuringFocus",()=>{assert.equal(ShelfBoard.remainsStationaryDuringFocus,true);assert.equal(BookFocusAnimator.shelfRemainsStationary,true);});
  it("focusedBookDoesNotCaptureNeighborClick",()=>{const selection=new BookSelectionController();selection.activate("a");assert.equal(BookInteractionRegion.activationFor(selection,"b",true),"selected");assert.equal(selection.selected(),"b");});
  it("focusedBookDoesNotCaptureEmptySpace",()=>{const selection=new BookSelectionController();selection.activate("a");assert.equal(BookInteractionRegion.activationFor(selection,"a",false),"ignored");assert.equal(selection.selected(),"a");});
  it("neighborClickChangesFocus",()=>{const selection=new BookSelectionController();selection.activate("a");BookInteractionRegion.activationFor(selection,"b",true);assert.equal(selection.state("a"),"RETURNING");assert.equal(selection.state("b"),"FOCUSING");});
  it("secondClickRequiresSameVisibleBook",()=>{const selection=new BookSelectionController();selection.activate("b");assert.equal(BookInteractionRegion.activationFor(selection,"b",false),"ignored");assert.equal(BookInteractionRegion.activationFor(selection,"b",true),"activated");});
  it("shelfBackgroundClickDoesNotOpenReader",()=>{const selection=new BookSelectionController();selection.activate("a");assert.equal(BookInteractionRegion.activationFor(selection,"a",false),"ignored");selection.deselect();assert.equal(selection.selected(),null);});
  it("bookSlotDoesNotActAsOversizedHitbox",()=>{assert.equal(BookInteractionRegion.structuralSlotCapturesPointer,false);assert.equal(BookShelfCard3D.usesDedicatedVisibleHitRegion,true);});
  it("dragStillDoesNotTriggerClick",()=>assert.equal(BookShelf.isTap(18,2),false));
  it("focusedExtractionPreservesOrientation",()=>assert.equal(BookFocusAnimator.preservesOrientation,true));
  it("focusedExtractionProtectsRightNeighbor",()=>assert.equal(BookFocusAnimator.protectsRightNeighbor,true));
  it("focusedExtractionStaysInItsSlot",()=>["mobile","tablet","desktop"].forEach(viewport=>assert.ok(Math.abs(BookFocusAnimator.vectorFor(viewport as "mobile"|"tablet"|"desktop").x)<=BookShelfCompactionLayout.focusLateralStepPixels+3)));
  it("focusedExtractionKeepsApprovedDepth",()=>assert.deepEqual([BookFocusAnimator.vectorFor("mobile").z,BookFocusAnimator.vectorFor("tablet").z,BookFocusAnimator.vectorFor("desktop").z],[0,0,0]));
  it("shelfBoardUsesIndependentPhysicalFaces",()=>{assert.notEqual(ShelfTopFace,ShelfFrontFace);assert.notEqual(ShelfEdgeHighlight,ShelfBottomShadow);});
  it("shelfBoardMobileThicknessIsPhysical",()=>assert.ok(ShelfBoard.mobileThicknessPixels>=23&&ShelfBoard.mobileThicknessPixels<=27));
  it("pageBlockHasTopSideAndInset",()=>{assert.equal(PageBlock3D.hasIndependentTopSideAndInset,true);assert.notEqual(PageTopFace,PageSideFace);assert.notEqual(PageSideFace,PageInset);});
  it("bookMatchesSpineDominantReference",()=>assert.equal(BookPerspectiveLayout.rotateY,81));
  it("bookHasPhysicalSpine",()=>assert.ok(new Book3DFactory().model(book("a","g"),"ANGLED").dimensions.spineRem>=3.6));
  it("bookHasPhysicalPageTop",()=>assert.equal(PageTopFace.hasCompressedLeafTexture,true));
  it("restingBookIsBehindShelfFrontEdge",()=>assert.equal(BookFocusAnimator.depthFor("RESTING","mobile"),-14));
  it("focusedBookPassesShelfFrontEdge",()=>assert.ok(BookFocusAnimator.focusedShelfOverhang>=5&&BookFocusAnimator.focusedShelfOverhang<=8));
  it("focusKeeps3DGeometry",()=>assert.equal(Book3D.isPhysicalBook,true));
  it("focusIncreasesBrightness",()=>{assert.equal(BookFocusAnimator.brightnessAt(0),.92);assert.equal(BookFocusAnimator.brightnessAt(.5),1);assert.equal(BookFocusAnimator.brightnessAt(1),1.07);});
  it("focusShadowMovesForward",()=>assert.equal(BookFocusAnimator.shadowTracksFocus,true));
  it("shelfHasTopDepth",()=>assert.ok(ShelfBoard.topDepthPixels>=10));
  it("shelfDarkensTowardBack",()=>assert.equal(ShelfBoard.darkensTowardBack,true));
  it("bookHasPhysicalPageBlock",()=>{assert.equal(PageBlock3D.hasIndependentTopSideAndInset,true);assert.notEqual(PageTopFace,PageSideFace);assert.notEqual(PageSideFace,PageFrontInset);});
  it("pageTopRemainsVisibleDuringFocus",()=>assert.equal(PageTopFace.preservesGeometryDuringFocus,true));
  it("bookKeepsRotationDuringFocus",()=>assert.equal(BookPerspectiveLayout.forCount(5).angle,BookPerspectiveLayout.forCount(5).selectedAngle));
  it("firstClickFocusesBook",()=>{const controller=new BookSelectionController();assert.equal(controller.activate("a"),"selected");assert.equal(controller.state("a"),"FOCUSING");});
  it("secondClickOpensReader",()=>{const controller=new BookSelectionController();controller.activate("a");assert.equal(controller.activate("a"),"activated");});
  it("focusedBookPassesShelfEdge",()=>assert.ok(BookFocusAnimator.focusedShelfOverhang>=5&&BookFocusAnimator.focusedShelfOverhang<=8));
  it("focusedBookKeeps3DGeometry",()=>{assert.equal(Book3D.isPhysicalBook,true);assert.notEqual(BookBottomFace,BookDepthFace);});
  it("contactShadowTracksFocus",()=>assert.equal(BookFocusAnimator.shadowTracksFocus,true));
  it("bookHitboxMatchesVisibleGeometry",()=>{assert.equal(BookInteractionRegion.structuralSlotCapturesPointer,false);assert.equal(BookInteractionRegion.secondClickRequiresVisibleFace,true);});
  it("bookContextMenuSupportsDeleteOnLongPressAndRightClick",()=>{assert.equal(BookShelfCard3D.supportsContextDelete,true);assert.ok(BookShelfCard3D.longPressDeleteMenuMs>=550);});
});

describe("GenreShelf", () => {
  it("booksGroupedByGenre", () => { const library = new Library([book("a", "terror"), book("b", "historia"), book("c", "terror")]); assert.deepEqual(library.findBooksByGenre("terror").map((item) => item.id), ["a", "c"]); });
  it("emptyGenreHidden", () => assert.equal(GenreShelf.shouldRender([]), false));
  it("newGenreWithBookAppears", () => { const library = new Library(); const genre = new Genre("engenharia", "Engenharia"); library.addGenre(genre); assert.equal(GenreShelf.shouldRender(library.findBooksByGenre(genre.id)), false);
    library.addBook(book("novo", genre.id)); assert.equal(GenreShelf.shouldRender(library.findBooksByGenre(genre.id)), true); });
});

describe("estante 3D — referência física", () => {
  it("camaraUnicaNaPrateleira", () => { assert.equal(BookPerspectiveLayout.cameraOwner, "SHELF_VIEWPORT"); assert.equal(BookPerspectiveLayout.referenceHeightRatio, .654); });
  it("focoParaAntesDaTesteira", () => { assert.equal(BookFocusAnimator.frontOverhangRatio, 0); (["mobile","tablet","desktop"] as const).forEach(v => assert.ok(BookFocusAnimator.vectorFor(v).y > 0)); });
  it("focoVemParaFrenteSemSubir", () => { assert.equal(BookFocusAnimator.neverRises, true); assert.ok(BookFocusAnimator.vectorFor("mobile").y > 0); assert.equal(BookFocusAnimator.scaleFor("FOCUSED"), 1); assert.equal(BookFocusAnimator.tiltFor("FOCUSED"), 0); assert.equal(BookFocusAnimator.focusTiltDegrees, 0); });
  it("FREIO PERMANENTE: nenhum NaN pode chegar ao transform via variavel CSS", () => {
    const raw = readFileSync(new URL("../src/components/BookFocusAnimator.ts", import.meta.url), "utf8");
    const src = raw.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");
    assert.equal(BookFocusAnimator.writesNoInlineExtraction, true);
    assert.deepEqual(BookFocusAnimator.finiteOrNull(1, 2), [1, 2]);
    assert.equal(BookFocusAnimator.finiteOrNull(1, Number.NaN), null);
    assert.equal(BookFocusAnimator.finiteOrNull(Number.POSITIVE_INFINITY), null);
    assert.ok(!/setProperty\(\s*["\`']--extract/.test(src), "animator voltou a escrever --extract inline");
    assert.ok(!/parseFloat\([^)]*perspective/.test(src), "animator voltou a ler perspective com parseFloat (vira NaN quando a camera e none)");
  });
  it("FREIO PERMANENTE: foco reusa a rotacao do repouso, sem tolerancia", () => {
    const css = readFileSync(new URL("../src/styles/book-physical.css", import.meta.url), "utf8");
    const audit = new BookFocusTransformAudit();
    const { resting, focused } = audit.audit(css);
    assert.equal(focused.rotateX, resting.rotateX, "rotateX mudou entre repouso e foco");
    assert.equal(focused.rotateY, resting.rotateY, "rotateY mudou entre repouso e foco");
    assert.equal(focused.rotateZ, resting.rotateZ, "rotateZ mudou entre repouso e foco");
    assert.equal(audit.rotationIsIdentical(css), true);
    assert.ok(!/skew/.test(audit.transformFor(css, BookFocusTransformAudit.focusedSelector)), "skew no transform de foco");
  });
  it("focoNaoGiraOLivro", () => { const p = BookPerspectiveLayout.forCount(5); assert.equal(BookFocusAnimator.angleFor("FOCUSED", p.angle, p.selectedAngle), BookFocusAnimator.angleFor("RESTING", p.angle, p.selectedAngle)); const v = BookFocusAnimator.vectorFor("mobile"); assert.equal(v.z, 0); assert.ok(v.x < 0); assert.ok(v.y > 0); assert.equal(BookFocusAnimator.tiltFor("FOCUSED"), 0); assert.equal(BookFocusAnimator.rigidTranslationOnly, true); assert.equal(BookFocusAnimator.advancesTowardViewer, true); });
  it("sombraPorLivroLimitadaAoVolume", () => { assert.equal(BookShadowLayer.boundedToVolumeFootprint, true); assert.equal(BookShadowLayer.hasHardContactLine, true); assert.equal(BookShadowLayer.staysOnShelfPlane, true); });
  it("margensLateraisIguais", () => { assert.equal(BookShelfCompactionLayout.startPaddingPixels, BookShelfCompactionLayout.endPaddingPixels); assert.equal(BookShelfCompactionLayout.startPaddingPixels, 10); assert.equal(BookShelfCompactionLayout.bleedsToViewportEdges, true); });
  it("linhaDeSombraFixaNoEspacoDaEstante",()=>{assert.equal(PageTopFace.shadeLineIsFixedInShelfSpace,true);assert.equal(PageTopFace.shadeLineHoldsDuringFocus,true);[0,.25,.5,1].forEach(p=>assert.equal(PageTopFace.litFrontAt(p),PageTopFace.litFrontAtRest));assert.equal(PageTopFace.litFrontAtFocus,PageTopFace.litFrontAtRest);});
  it("anguloIdenticoEntreRepousoEFoco",()=>{const p=BookPerspectiveLayout.forCount(5);assert.equal(p.angle,p.selectedAngle);assert.equal(BookFocusAnimator.angleFor("FOCUSED",p.angle,p.selectedAngle),BookFocusAnimator.angleFor("RESTING",p.angle,p.selectedAngle));[1,2,3,7,12].forEach(n=>{const q=BookPerspectiveLayout.forCount(n);assert.equal(q.angle,q.selectedAngle);});});
  it("caudaDoCarrosselAcompanhaAProjecao",()=>{assert.equal(BookShelfCompactionLayout.trailingSlotTracksProjectedFootprint,true);assert.ok(BookShelfCompactionLayout.footprintRatio<1&&BookShelfCompactionLayout.footprintRatio>.5);});
  it("topoDePaginasEscureceParaOFundo", () => { assert.equal(PageTopFace.depthRampRunsFrontToBack, true); assert.ok(PageTopFace.litFrontFraction <= .3 && PageTopFace.litFrontFraction >= .2);assert.equal(PageTopFace.rampRunsAlongDepth,true);assert.equal(PageTopFace.hasLateralSplit,false); });
  it("lombadaTemPerfilArredondado", () => { assert.equal(BookSpineBevel.roundsSpineProfile, true); });
  it("bordaDeAberturaNaoUsaCapaDura", () => { assert.equal(BookDepthFace.isOpeningEdge, true); assert.equal(BookDepthFace.usesCaseMaterial, false); assert.equal(BookDepthFace.usesPageMaterial, true); });
  it("testeiraDobrouSemMexerNaBandeja", () => { assert.equal(ShelfBoard.frontFaceRemUnits, 1.9); assert.ok(ShelfBoard.trayDepthPixels >= 24 && ShelfBoard.trayDepthPixels <= 30); });
  it("sombraDaMadeiraCresceAoChegarNaPonta", () => {
    assert.equal(BookWoodShadow.matchesBookWidth, true);
    assert.equal(BookWoodShadow.leansLeftOnTheBoard, true);
    assert.equal(BookWoodShadow.fadesOutOnBoardCorner, true);
    assert.equal(BookWoodShadow.reachesFrontFaceBottom, true);
    assert.equal(BookWoodShadow.collapsesOntoCorner, true);
    assert.equal(BookWoodShadow.returnCutsOutInOneStep, true);
    assert.ok(BookWoodShadow.returnSnapMs > 0 && BookWoodShadow.returnSnapMs <= 120);
  });
  it("os volumes ficam assentados na luz da baia, nao estourados", () => {
    const css = readFileSync(new URL("../src/styles/book-physical.css", import.meta.url), "utf8");
    assert.equal(BookSpinePaletteService.brightensLightBoards, false);
    assert.ok(BookSpinePaletteService.boardLuminanceCeiling <= 190);
    const service = new BookSpinePaletteService();
    const light = service.fallbackPalette("rgb(236, 228, 205)");
    const channels = light.background.match(/\d+/g)!.map(Number);
    const luma = .2126 * channels[0]! + .7152 * channels[1]! + .0722 * channels[2]!;
    assert.ok(luma <= BookSpinePaletteService.boardLuminanceCeiling + 1, `board luma ${luma}`);
    assert.equal(light.ink, BookSpinePaletteService.darkInk);
    assert.ok(css.includes(PageTopFace.litBandHex));
    assert.ok(!css.includes("#fdf6e1"));
    assert.ok(css.includes(`brightness(${String(BookSpineFace.artBrightness).replace("0.", ".")})`));
    assert.deepEqual([...BookWoodShadow.mirrorEasing(.2, .3, .6, .88)], [.4, .12, .8, .7]);
    const forward = BookWoodShadow.forwardEasing.match(/[\d.]+/g)!.map(Number);
    const back = BookWoodShadow.returnEasing.match(/[\d.]+/g)!.map(Number);
    assert.deepEqual(back, [...BookWoodShadow.mirrorEasing(forward[0]!, forward[1]!, forward[2]!, forward[3]!)]);
  });
  it("sombraDaMadeiraReageAoFoco", () => { assert.equal(BookWoodShadow.reactsToFocusProgress, true); assert.equal(BookWoodShadow.absentAtRest, true); });
  it("faixaClaraFicaNosPrimeiros25PorCentoDaFrente", () => { assert.equal(PageTopFace.litFrontAtRest, .25); assert.equal(PageTopFace.rampRunsAlongDepth, true); });
  it("testeiraLacada", () => { assert.equal(ShelfBoard.hasLacqueredFrontFace, true); assert.equal(ShelfBoard.hasPhysicalTopFace, true); });
  it("lombadaEscalaTipoPelaLarguraReal", () => { const wide = BookSpineFace.typeScale("A"); const narrow = BookSpineFace.typeScale("PROSPERIDADE"); assert.ok(wide.includes("--physical-depth")); assert.notEqual(wide, narrow); });
  it("lombadaNaoInventaOrnamento", () => { assert.equal(BookSpineFace.inventsNoOrnament, true); assert.equal(BookSpineFace.derivesColoursFromCover, true);  });
  it("subtituloSoUsaSerieReal", () => { const base = new Book3DFactory().model(book("a", "g"), "ANGLED"); assert.equal(BookSpineFace.subtitleFor(base), undefined); assert.equal(BookSpineFace.subtitleFor({ ...base, series: "Livro a" }), undefined); assert.equal(BookSpineFace.subtitleFor({ ...base, series: "Colecao Ouro" }), "Colecao Ouro"); });
  it("paletaDaLombadaVemDaCapa", () => { const service = new BookSpinePaletteService(); const dark = service.fromSamples([250, 210, 90, 255, 12, 10, 14, 255], "rgb(20, 18, 26)"); assert.notEqual(dark.ink, BookSpinePaletteService.lightInk); assert.ok(dark.ink.startsWith("rgb(")); const flat = service.fromSamples([21, 19, 27, 255], "rgb(20, 18, 26)"); assert.equal(flat.ink, BookSpinePaletteService.lightInk); });
  it("tintaClaraSobreFundoClaro", () => { assert.equal(new BookSpinePaletteService().fallbackPalette("rgb(230, 224, 200)").ink, BookSpinePaletteService.darkInk); });
  it("lombadaTemColofaoDaAplicacao", () => { assert.equal(BookSpineFace.imprintCarriesAppMark, true); assert.deepEqual([...BookSpineFace.zones], ["author", "art", "title", "subtitle", "imprint"]); });
  it("lombadaUsaAImagemRealComprimida", () => { assert.equal(BookSpineFace.usesRasterCoverArt, true); assert.equal(BookSpineFace.compressesCoverProportionally, true); assert.equal(BookSpineFace.stretchesCover, false); assert.equal(BookSpineFace.usesGeneratedTypography, true); });
});
