import assert from "node:assert/strict";import{describe,it}from"node:test";
import{DocumentTypeDetector}from"../src/reader/reflow/DocumentTypeDetector";import{TextLayoutEngine}from"../src/reader/reflow/TextLayoutEngine";import{PaginationEngine}from"../src/reader/reflow/PaginationEngine";import{PageTurnController}from"../src/reader/reflow/PageTurnController";import{ImageDocumentEnhancer}from"../src/reader/reflow/ImageDocumentEnhancer";import{PaperThemeManager}from"../src/reader/reflow/PaperThemeManager";import type{StorageAdapter}from"../src/services/StorageService";import type{PDFDocumentProxy}from"pdfjs-dist";
import{LimaReaderEngine}from"../src/lima/LimaReaderEngine";import{LimaDocument}from"../src/lima/LimaDocument";
const pdf=(counts:number[])=>({numPages:counts.length,getPage:async(page:number)=>({getTextContent:async()=>({items:[{str:"x".repeat(counts[page-1]??0)}]})})})as unknown as PDFDocumentProxy;
describe("DocumentTypeDetector",()=>{it("detecta PDF textual por amostragem",async()=>assert.equal(await new DocumentTypeDetector().detect(pdf([100,100,100])),"TEXT_BASED"));it("detecta PDF escaneado",async()=>assert.equal(await new DocumentTypeDetector().detect(pdf([0,2,0])),"IMAGE_BASED"));it("detecta documento misto",async()=>assert.equal(await new DocumentTypeDetector().detect(pdf([100,0,100])),"MIXED"));});
describe("layout e paginação reflow",()=>{const document=new TextLayoutEngine().layout(Array.from({length:30},(_,i)=>({text:`Parágrafo ${i} ${"conteúdo ".repeat(25)}`,page:Math.floor(i/5)+1,fontSize:i%8===0?20:12,lineBreak:true})));
  it("reconstrói parágrafos e títulos",()=>{assert.equal(document.paragraphs.length,30);assert.equal(document.paragraphs[0]?.kind,"heading")});
  it("aumentar fonte repagina para mais páginas",()=>{const engine=new PaginationEngine(),small=engine.paginate(document,{width:390,height:844,fontSize:16,lineHeight:1.5,margin:24}),large=engine.paginate(document,{width:390,height:844,fontSize:28,lineHeight:1.8,margin:24});assert.ok(large.length>small.length)});
  it("preserva posição lógica após repaginar",()=>{const engine=new PaginationEngine(),anchor={paragraphId:"p",textOffset:0,logicalOffset:1800},first=engine.paginate(document,{width:390,height:844,fontSize:16,lineHeight:1.5,margin:24}),second=engine.paginate(document,{width:390,height:844,fontSize:26,lineHeight:1.7,margin:24});assert.ok(first[engine.pageForAnchor(first,anchor)]!.startOffset<=1800);assert.ok(second[engine.pageForAnchor(second,anchor)]!.startOffset<=1800)});
  it("o parágrafo continua na página seguinte sem deixar órfã nem viúva",()=>{const doc=new TextLayoutEngine().layout([{text:"Curto.",page:1,fontSize:12,lineBreak:true},{text:"Palavra ".repeat(95),page:1,fontSize:12,lineBreak:true},{text:"Último bloco.",page:1,fontSize:12,lineBreak:true}]),pages=new PaginationEngine().paginate(doc,{width:320,height:360,fontSize:20,lineHeight:1.6,margin:22});assert.ok(pages.length>1);// a primeira pagina nao fica com o resto em branco: o paragrafo longo comeca nela e continua na seguinte
assert.equal(pages[0]?.paragraphs.at(-1)?.sourceBlockId,"p-1","o espaco que sobra na pagina e usado");assert.equal(pages[1]?.paragraphs[0]?.sourceBlockId,"p-1");const perLine=Math.floor((320-44)/(20*.52)),lines=(text:string)=>{let n=1,c=0;for(const w of text.split(/\s+/).filter(Boolean)){const next=(c?c+1:0)+w.length;if(next>perLine&&c>0){n++;c=w.length;}else c=next;}return n;};for(const page of pages)for(const piece of page.paragraphs)if(piece.sourceBlockId==="p-1")assert.ok(lines(piece.text)>=PaginationEngine.minLines,`pedaco com ${lines(piece.text)} linha`);// e nada do texto se perde nem se repete na divisao
const joined=pages.flatMap(page=>page.paragraphs).filter(piece=>piece.sourceBlockId==="p-1").map(piece=>piece.text).join(" ");assert.equal(joined.replace(/\s+/g," ").trim(),"Palavra ".repeat(95).trim());});
  it("divide parágrafo gigante somente em fronteira de palavra",()=>{const doc=new TextLayoutEngine().layout([{text:Array.from({length:240},(_,i)=>`palavra${i}`).join(" "),page:1,fontSize:12,lineBreak:true}]),pages=new PaginationEngine().paginate(doc,{width:300,height:260,fontSize:22,lineHeight:1.6,margin:18});assert.ok(pages.length>1);for(const page of pages){for(const paragraph of page.paragraphs){assert.doesNotMatch(paragraph.text,/^\s|\s$/);assert.match(paragraph.text,/^palavra\d+( palavra\d+)*$/);}}});
  it("capa é primeira página e conteúdo começa depois dela",()=>{const engine=new PaginationEngine(),pages=engine.withCover(engine.paginate(document,{width:390,height:844,fontSize:16,lineHeight:1.5,margin:24}),{title:"Livro",image:"cover.png"});assert.equal(pages[0]?.cover?.title,"Livro");assert.equal(pages[1]?.paragraphs[0]?.kind,"heading");assert.equal(engine.pageForAnchor(pages,{paragraphId:"p-0",textOffset:0,logicalOffset:0}),1)});
  it("mantém a relação página física e folhas visuais 1A/1B",()=>{const source=new TextLayoutEngine().layout([{text:"uma ".repeat(250),page:1,fontSize:12,lineBreak:true},{text:"duas ".repeat(250),page:2,fontSize:12,lineBreak:true}]),pages=new PaginationEngine().paginate(source,{width:300,height:260,fontSize:22,lineHeight:1.7,margin:18});assert.ok(pages.some(page=>page.visualLabel==="1A"));assert.ok(pages.some(page=>page.visualLabel==="1B"));assert.ok(pages.some(page=>page.visualLabel==="2A"));for(const page of pages){assert.equal(new Set(page.paragraphs.map(value=>value.sourcePage)).size,1);assert.match(page.visualLabel??"",/^\d+[A-Z]+$/);}});
  it("preserva a capa como primeira folha durante repaginação inicial",()=>{const lima=new LimaDocument({format:"lima",version:1,documentId:"doc",createdAt:"",generator:"test",sourceFormat:"pdf",capabilities:{reflow:true,images:false,chapters:false,highlights:true,annotations:true,search:true}},{id:"doc",title:"Livro",author:"Autor",language:"pt-BR",genre:"",sourceFormat:"pdf",createdAt:""},[],[{id:"p-0",type:"paragraph",order:0,content:"texto ".repeat(300),chapterId:""}],[],[]),reader=new LimaReaderEngine(),metrics={width:320,height:420,fontSize:18,lineHeight:1.6,margin:20};reader.open(lima,metrics,undefined,{title:"Livro"},true);reader.repaginate({...metrics,fontSize:24});assert.ok(reader.currentPage.cover);reader.next();reader.repaginate(metrics);assert.equal(reader.currentPage.cover,undefined);});
});
describe("gesto e papel",()=>{it("dragProgress é progressivo e limitado",()=>{const controller=new PageTurnController({}as HTMLElement,{}as never,()=>{},()=>{});assert.equal(controller.dragProgress(50,200),.25);assert.equal(controller.dragProgress(400,200),1)});it("melhoria de scan permanece local em CSS",()=>assert.match(new ImageDocumentEnhancer().css({brightness:95,contrast:110,grayscale:true,threshold:10}),/grayscale\(100%\)/));it("persiste papel escolhido",async()=>{const values=new Map<string,unknown>();const storage:StorageAdapter={load:async k=>(values.get(k)??null)as never,save:async(k,v)=>{values.set(k,v)},remove:async k=>{values.delete(k)}};const paper=new PaperThemeManager(storage as never);await paper.set("sepia");const restored=new PaperThemeManager(storage as never);await restored.initialize();assert.equal(restored.value,"sepia")});});
