import{getDocument,type PDFDocumentLoadingTask,type PDFDocumentProxy,type RenderTask}from"pdfjs-dist";import type{PasswordProvider}from"../PdfReaderEngine";import type{ReaderSettings}from"../ReaderSettingsManager";import type{ReaderStageSize}from"../PdfPageRenderer";import{RenderedPageCache}from"./RenderedPageCache";import{ScanEnhancementPipeline,type ScanEnhancementSettings}from"./ScanEnhancementPipeline";

export class ImagePageReaderEngine{
  private task:PDFDocumentLoadingTask|null=null;private document:PDFDocumentProxy|null=null;private active:RenderTask|null=null;private readonly cache=new RenderedPageCache(4);private readonly maxCanvasPixels=18_000_000;
  public async open(blob:Blob,_passwordProvider?:PasswordProvider):Promise<void>{await this.close();this.task=getDocument({data:await blob.arrayBuffer()});this.document=await this.task.promise;}
  public get totalPages():number{return this.document?.numPages??0;}
  public async render(pageNumber:number,target:HTMLCanvasElement,settings:Readonly<ReaderSettings>,stage:ReaderStageSize,scan:ScanEnhancementSettings):Promise<boolean>{const cached=this.cache.get(pageNumber);if(cached){this.copy(cached.canvas,target);this.applyFilter(target,scan);this.preloadAdjacent(pageNumber,settings,stage,scan);return true;}const page=await this.getPage(pageNumber),canvas=await this.renderCanvas(pageNumber,page,settings,stage,scan);this.copy(canvas,target);this.applyFilter(target,scan);this.preloadAdjacent(pageNumber,settings,stage,scan);return true;}
  public async preloadAdjacent(pageNumber:number,settings:Readonly<ReaderSettings>,stage:ReaderStageSize,scan:ScanEnhancementSettings):Promise<void>{for(const value of [pageNumber-1,pageNumber+1,pageNumber+2])if(value>=1&&value<=this.totalPages&&!this.cache.has(value))void this.getPage(value).then(page=>this.renderCanvas(value,page,settings,stage,scan)).catch(()=>undefined);}
  public cancel():void{this.active?.cancel();this.active=null;}
  public async close():Promise<void>{this.cancel();this.cache.clear();await this.task?.destroy();this.task=null;this.document=null;}
  private async getPage(pageNumber:number){if(!this.document)throw new Error("O PDF ainda não foi carregado.");return this.document.getPage(pageNumber);}
  private async renderCanvas(pageNumber:number,page:Awaited<ReturnType<PDFDocumentProxy["getPage"]>>,settings:Readonly<ReaderSettings>,stage:ReaderStageSize,scan:ScanEnhancementSettings):Promise<HTMLCanvasElement>{const base=page.getViewport({scale:1}),availableWidth=Math.max(240,stage.width-24),availableHeight=Math.max(240,stage.height-24);let scale=settings.zoom/100;if(settings.fitMode==="width")scale=availableWidth/base.width;if(settings.fitMode==="page")scale=Math.min(availableWidth/base.width,availableHeight/base.height);const viewport=page.getViewport({scale}),ratio=Math.min(globalThis.devicePixelRatio||1,2.5),safeRatio=Math.max(1,Math.min(ratio,Math.sqrt(this.maxCanvasPixels/Math.max(1,viewport.width*viewport.height)))),canvas=document.createElement("canvas");canvas.width=Math.floor(viewport.width*safeRatio);canvas.height=Math.floor(viewport.height*safeRatio);canvas.style.width=`${Math.floor(viewport.width)}px`;canvas.style.height=`${Math.floor(viewport.height)}px`;const context=canvas.getContext("2d",{alpha:false});if(!context)throw new Error("Não foi possível renderizar esta página.");const task=page.render({canvas,canvasContext:context,viewport,transform:safeRatio===1?undefined:[safeRatio,0,0,safeRatio,0,0]});this.active=task;try{await task.promise;this.applyFilter(canvas,scan);this.cache.set({pageNumber,canvas,createdAt:Date.now()});return canvas;}finally{if(this.active===task)this.active=null;page.cleanup();}}
  private copy(source:HTMLCanvasElement,target:HTMLCanvasElement):void{target.width=source.width;target.height=source.height;target.style.width=source.style.width;target.style.height=source.style.height;const context=target.getContext("2d",{alpha:false});if(!context)throw new Error("Não foi possível renderizar esta página.");context.drawImage(source,0,0);}
  private applyFilter(canvas:HTMLCanvasElement,scan:ScanEnhancementSettings):void{canvas.style.filter=new ScanEnhancementPipeline().filter(scan);}
}
