import type { ContextResult } from "../services/study/ContextLookupService";
import type { DefinitionResult, StudyLanguage, TranslationResult } from "../services/study/StudyLookupTypes";
import { I18nManager } from "../i18n/I18nManager";

export class StudyLookupPanel { private panel: HTMLElement | null = null; private content: HTMLElement | null = null; private readonly i18n = I18nManager.shared;
  public render(): HTMLElement { const panel = document.createElement("aside"); this.panel = panel; panel.className = "study-lookup-panel"; panel.setAttribute("aria-hidden", "true"); panel.setAttribute("aria-live", "polite"); const header = document.createElement("header"), title = document.createElement("h2"), close = document.createElement("button"); title.textContent = this.i18n.t("ui.study.studyExcerpt"); close.type = "button"; close.textContent = "×"; close.setAttribute("aria-label", this.i18n.t("ui.common.close")); close.addEventListener("click", () => this.close()); header.append(title, close); this.content = document.createElement("div"); panel.append(header, this.content); return panel; }
  public loading(label: string): void { this.open(); if (this.content) this.content.textContent = label; }
  public definition(value: DefinitionResult): void { this.show(this.i18n.t("selection.dictionary"), value.definition, value.origin ? `${this.i18n.t("selection.origin")}: ${value.origin}` : undefined, this.i18n.t("ui.study.source", { source: value.source })); }
  public translation(value: TranslationResult): void { this.open(); if (!this.content) return; this.content.replaceChildren(this.heading(this.i18n.t("ui.study.original")), this.text(value.original), this.heading(this.i18n.t("ui.study.translation")), this.text(value.translated), this.text(this.i18n.t("ui.study.source", { source: value.source }))); }
  public context(value: ContextResult): void { this.open(); if (!this.content) return; this.content.replaceChildren(this.heading(this.i18n.t("selection.context"))); if (value.title) this.content.append(this.text(value.title)); if (value.previous) this.content.append(this.text(value.previous)); const current = this.text(value.current); current.className = "study-lookup-current"; this.content.append(current); if (value.next) this.content.append(this.text(value.next)); }
  public origin(value: string): void { this.show(this.i18n.t("ui.study.wordOrigin"), value); }
  public error(message: string, retry: () => void): void { this.open(); if (!this.content) return; const button = document.createElement("button"); button.type = "button"; button.textContent = this.i18n.t("ui.common.retry"); button.addEventListener("click", retry); this.content.replaceChildren(this.text(message), button); }
  public languagePicker(current: StudyLanguage, action: (language: StudyLanguage) => void): void { this.open(); if (!this.content) return; const label = document.createElement("label"); label.textContent = this.i18n.t("ui.study.targetLanguage"); const select = document.createElement("select"); [["pt-BR", this.i18n.t("ui.study.portuguese")], ["en", this.i18n.t("ui.study.english")], ["es", this.i18n.t("ui.study.spanish")]].forEach(([value, text]) => select.append(new Option(text, value))); select.value = current; const button = document.createElement("button"); button.type = "button"; button.textContent = this.i18n.t("selection.translate"); button.addEventListener("click", () => action(select.value as StudyLanguage)); label.append(select); this.content.replaceChildren(label, button); }
  public close(): void { this.panel?.classList.remove("study-lookup-panel--open"); this.panel?.setAttribute("aria-hidden", "true"); document.body.classList.remove("study-lookup-open"); }
  private open(): void { this.panel?.classList.add("study-lookup-panel--open"); this.panel?.setAttribute("aria-hidden", "false"); document.body.classList.add("study-lookup-open"); }
  private show(title: string, ...lines: (string | undefined)[]): void { this.open(); if (this.content) this.content.replaceChildren(this.heading(title), ...lines.filter((line): line is string => Boolean(line)).map(line => this.text(line))); }
  private heading(text: string): HTMLElement { const heading = document.createElement("h3"); heading.textContent = text; return heading; }
  private text(text: string): HTMLElement { const paragraph = document.createElement("p"); paragraph.textContent = text; return paragraph; }
}
