/** Shared, reviewed interface copy. Book titles, author names and book text never belong here. */
export const INTERFACE_PT = {
  "ui.brand.tagline": "Leia · Evolua · Transforme",
  "ui.navigate.home": "Ir para o início", "ui.navigation.main": "Navegação principal", "ui.navigation.mobile": "Navegação mobile", "ui.navigation.bottom": "Navegação inferior",
  "ui.navigation.closeMenu": "Fechar menu", "ui.navigation.menu": "Menu principal", "ui.navigation.library": "Biblioteca", "ui.navigation.home": "Início", "ui.navigation.add": "Adicionar", "ui.navigation.settings": "Ajustes", "ui.navigation.logout": "Sair",
  "ui.greeting.hello": "Olá, {name}!", "ui.greeting.goodReading": "Boa leitura", "ui.auth.waiting": "Sua biblioteca espera", "ui.auth.startNow": "Comece agora",
  "ui.auth.login": "Entrar", "ui.auth.register": "Criar conta", "ui.auth.email": "E-mail", "ui.auth.password": "Senha", "ui.auth.confirmPassword": "Confirmar senha", "ui.auth.haveAccount": "Já tenho uma conta",
  "ui.auth.localOptional": "Opcional no modo local", "ui.auth.loginFailed": "Não foi possível entrar.", "ui.auth.registerFailed": "Não foi possível criar a conta.", "ui.auth.passwordMismatch": "As senhas não coincidem.", "ui.auth.passwordMinimum": "Use pelo menos 8 caracteres.", "ui.auth.confirmEmail": "Confira seu e-mail para confirmar a conta.", "ui.auth.or": "ou", "ui.auth.google.continue": "Continuar com Google", "ui.auth.google.notConfigured": "O login com Google ainda não está configurado.", "ui.auth.google.unavailable": "Não foi possível carregar o login do Google. Verifique a conexão e tente novamente.", "ui.auth.google.failed": "Não foi possível entrar com o Google.", "ui.device.googleAccountMismatch": "Essa conta Google é diferente da conta que está usando o Lumeo. Entre de novo com a conta certa.",
  "ui.home.title": "Sua próxima história está aqui.", "ui.home.openLibrary": "Abrir minha biblioteca", "ui.home.myLibrary": "Minha biblioteca", "ui.home.openHint": "Toque no livro para abrir", "ui.home.addBook": "+ Adicionar livro", "ui.home.booksSaved": "{count} livro guardado|{count} livros guardados", "ui.home.booksSavedSuffix": "no seu ambiente de leitura.",
  "ui.library.title": "Minha Biblioteca", "ui.library.subtitle": "Grandes ideias, uma vida extraordinária.", "ui.library.search": "Buscar livros", "ui.library.searchPlaceholder": "Buscar livros…", "ui.library.noGenres": "Sua biblioteca ainda não tem gêneros.", "ui.library.addFirst": "Adicione um livro para montar sua primeira prateleira.", "ui.library.back": "← Voltar à biblioteca", "ui.library.notFoundGenre": "Gênero não encontrado", "ui.library.collectionBooks": "{count} livro nesta coleção.|{count} livros nesta coleção.", "ui.library.emptyGenre": "Nenhum livro neste gênero ainda.",
  "ui.book.notFound": "Livro não encontrado", "ui.book.noGenre": "Sem gênero", "ui.book.unknownAuthor": "Autor desconhecido", "ui.book.read": "Ler", "ui.book.edit": "Editar", "ui.book.format": "Formato", "ui.book.size": "Tamanho", "ui.book.status": "Status", "ui.book.unread": "Não iniciado", "ui.book.reading": "Lendo", "ui.book.finished": "Concluído", "ui.book.locateFile": "Localizar arquivo", "ui.book.fileMissing": "Arquivo local não encontrado.", "ui.book.fileInvalid": "O arquivo local não pôde ser validado.", "ui.book.deleteConfirm": "Excluir “{title}” e o arquivo armazenado?",
  "ui.edit.title": "Editar livro", "ui.edit.bookTitle": "Título", "ui.edit.author": "Autor", "ui.edit.genre": "Gênero", "ui.edit.newGenre": "Novo gênero", "ui.edit.createGenre": "+ Criar gênero", "ui.edit.changeCover": "Trocar capa", "ui.edit.saveChanges": "Salvar alterações", "ui.edit.saveFailed": "Não foi possível salvar.",
  "ui.onboarding.customize": "Seu espaço, do seu jeito", "ui.onboarding.prepare": "Vamos preparar seu ambiente de leitura?", "ui.onboarding.organize": "Como quer organizar seus livros?", "ui.onboarding.organizeHelp": "Você poderá alterar e criar novos gêneros depois.", "ui.onboarding.allGenres": "Quero todos os gêneros", "ui.onboarding.allGenresHelp": "Começar com a seleção completa", "ui.onboarding.chooseGenres": "Escolher meus gêneros", "ui.onboarding.chooseGenresHelp": "Marcar apenas os que combinam comigo", "ui.onboarding.customGenres": "Criar meus próprios", "ui.onboarding.customGenresHelp": "Começar com categorias personalizadas", "ui.onboarding.selectGenres": "Selecionar gêneros", "ui.onboarding.yourSelection": "Sua seleção", "ui.onboarding.noGenres": "Nenhum gênero selecionado ainda", "ui.onboarding.customGenreLabel": "Gêneros personalizados", "ui.onboarding.customGenreHelp": "Digite um nome e ele aparecerá na sua seleção.", "ui.onboarding.customGenrePlaceholder": "Ex.: Poesia brasileira", "ui.onboarding.appearance": "Escolha a aparência", "ui.onboarding.finish": "Preparar minha biblioteca", "ui.onboarding.chooseOne": "Escolha pelo menos um gênero para continuar.", "ui.onboarding.removeGenre": "Remover {name}",
  "ui.common.back": "Voltar", "ui.common.cancel": "Cancelar", "ui.common.close": "Fechar", "ui.common.save": "Salvar", "ui.common.delete": "Excluir", "ui.common.edit": "Editar", "ui.common.add": "Adicionar", "ui.common.remove": "Remover", "ui.common.open": "Abrir", "ui.common.retry": "Tentar novamente", "ui.common.search": "Pesquisar", "ui.common.loading": "Carregando…", "ui.common.preparing": "Preparando…", "ui.common.optional": "Opcional", "ui.common.confirm": "Confirmar", "ui.common.yes": "Sim", "ui.common.no": "Não",
  "ui.import.title": "Adicionar livro", "ui.import.selectFile": "Selecionar arquivo", "ui.import.importing": "Importando…", "ui.import.validating": "Validando arquivo…", "ui.import.complete": "Importação concluída.", "ui.import.invalidFile": "Arquivo inválido.", "ui.import.pdfEpub": "Escolha um PDF ou EPUB", "ui.import.fromDevice": "Do dispositivo", "ui.import.fromGoogle": "Google Drive", "ui.import.fromOneDrive": "OneDrive",
  "ui.catalog.eyebrow": "Catálogo", "ui.catalog.title": "Explorar livros", "ui.catalog.subtitle": "Adicione à sua biblioteca somente os livros que deseja guardar neste dispositivo.", "ui.catalog.search": "Buscar por título, autor, gênero ou coleção", "ui.catalog.allGenres": "Todos os gêneros", "ui.catalog.loadMore": "Carregar mais", "ui.catalog.empty": "Nenhum livro foi encontrado no catálogo.", "ui.catalog.offline": "Catálogo indisponível sem conexão.", "ui.catalog.coverOf": "Capa de {title}", "ui.catalog.add": "Adicionar à biblioteca", "ui.catalog.inLibrary": "Na biblioteca", "ui.catalog.open": "Abrir livro", "ui.catalog.volume": "Volume {volume}", "ui.catalog.genre": "Gênero", "ui.catalog.format": "Formato", "ui.catalog.size": "Tamanho", "ui.catalog.collection": "Coleção", "ui.catalog.volumeLabel": "Volume", "ui.catalog.preparing": "Preparando…", "ui.catalog.downloading": "Baixando…", "ui.catalog.validating": "Validando…", "ui.catalog.saving": "Salvando…", "ui.catalog.complete": "Pronto.", "ui.catalog.failed": "Não foi possível adicionar o livro.", "ui.catalog.adminTitle": "Administração do catálogo", "ui.catalog.adminHelp": "A sincronização lê somente a pasta autorizada e não baixa livros para os dispositivos.", "ui.catalog.adminDenied": "Esta conta não pode administrar o catálogo.", "ui.catalog.sync": "Sincronizar catálogo", "ui.catalog.syncing": "Sincronizando catálogo…", "ui.catalog.syncResult": "Concluído: {total} arquivos · {created} novos · {updated} atualizados · {duplicates} duplicados · {failures} falhas.",
  "ui.settings.title": "Configurações", "ui.settings.preferences": "Preferências", "ui.settings.appearance": "Aparência", "ui.settings.appearanceHelp": "Escolha como o Lumeo deve aparecer neste dispositivo.", "ui.settings.lightTheme": "Tema claro", "ui.settings.darkTheme": "Tema escuro", "ui.settings.chooseFolder": "Escolher pasta da biblioteca", "ui.settings.authorizeFolder": "Autorizar pasta", "ui.settings.folderAuthorized": "Pasta da biblioteca autorizada.", "ui.settings.folderCancelled": "A seleção da pasta foi cancelada.", "ui.settings.folderPermission": "A biblioteca está nesta pasta. Autorize o acesso para continuar.",
  "ui.pwa.installLumeo": "Instalar o Lumeo", "ui.pwa.installApp": "Instalar app", "ui.pwa.installed": "O Lumeo já está instalado neste dispositivo.", "ui.pwa.installDescription": "Tenha o Lumeo na tela inicial, abrindo em tela cheia e funcionando sem internet.", "ui.pwa.safariInstall": "No Safari, toque em Compartilhar e depois em “Adicionar à Tela de Início”.", "ui.pwa.browserInstall": "Abra o menu do navegador e escolha “Instalar app” ou “Adicionar à tela inicial”.", "ui.pwa.installing": "Instalando o Lumeo…",
  "ui.reader.adaptiveOnly": "Disponível no modo de leitura adaptável.", "ui.reader.spreadAvailable": "Disponível em telas a partir de 768 px", "ui.reader.openSheet": "Abrir fichário", "ui.reader.coverOf": "Capa de {title}", "ui.reader.pdfPassword": "Não foi possível abrir o PDF com essa senha.", "ui.reader.pdfInvalid": "O PDF parece inválido ou corrompido. Tente importá-lo novamente.",
  "ui.study.notebook": "Caderno", "ui.study.closeNotebook": "Fechar Caderno", "ui.study.yourStudy": "Seu estudo neste livro", "ui.study.show": "Exibir", "ui.study.all": "Tudo", "ui.study.highlights": "Grifos", "ui.study.notes": "Notas", "ui.study.bookmarks": "Marcadores", "ui.study.color": "Cor", "ui.study.allColors": "Todas as cores", "ui.study.sort": "Ordenar", "ui.study.bookOrder": "Ordem do livro", "ui.study.newest": "Mais recentes", "ui.study.oldest": "Mais antigos", "ui.study.searchMarks": "Buscar nas marcações", "ui.study.groupChapter": "Agrupar por capítulo", "ui.study.review": "Revisar", "ui.study.startReview": "Iniciar revisão", "ui.study.noMarks": "Nenhuma marcação encontrada.", "ui.study.editNote": "Editar nota", "ui.study.removeEntry": "Remover entrada", "ui.study.previous": "Anterior", "ui.study.next": "Próxima", "ui.study.exit": "Sair", "ui.study.openInBook": "Abrir no livro",
  "ui.study.marksTitle": "Marcações", "ui.study.closeMarks": "Fechar marcações", "ui.study.noMark": "Nenhuma marcação.", "ui.study.resumeHere": "Parei aqui", "ui.study.position": "Posição {position}", "ui.study.studyExcerpt": "Estudar trecho", "ui.study.original": "Original", "ui.study.translation": "Tradução", "ui.study.source": "Fonte: {source}", "ui.study.wordOrigin": "Origem da palavra", "ui.study.targetLanguage": "Idioma de destino", "ui.study.portuguese": "Português", "ui.study.english": "Inglês", "ui.study.spanish": "Espanhol", "ui.study.addNote": "Adicionar nota", "ui.study.lookupDefinition": "Consultar significado", "ui.study.translateExcerpt": "Traduzir trecho", "ui.study.searchWeb": "Pesquisar na web",
  "ui.chapter.sheet": "Fichário do capítulo", "ui.chapter.closeSheet": "Fechar fichário", "ui.chapter.search": "Buscar neste fichário", "ui.chapter.saving": "Salvando…", "ui.chapter.saved": "Salvo", "ui.chapter.summary": "Meu resumo", "ui.chapter.writeWords": "Escreva com suas palavras…", "ui.chapter.topics": "Tópicos principais", "ui.chapter.newTopic": "Novo tópico", "ui.chapter.questions": "Perguntas", "ui.chapter.newQuestion": "Nova pergunta", "ui.chapter.optionalAnswer": "Resposta opcional", "ui.chapter.doubts": "Dúvidas", "ui.chapter.registerDoubt": "Registrar dúvida", "ui.chapter.optionalObservation": "Observação opcional", "ui.chapter.marks": "Marcações deste capítulo", "ui.chapter.noMarks": "Nenhuma marcação neste capítulo.", "ui.chapter.review": "Revisar capítulo", "ui.chapter.noQuestions": "Nenhuma pergunta criada.", "ui.chapter.noAnswer": "Sem resposta registrada.", "ui.chapter.seeAnswer": "Ver resposta", "ui.chapter.openExcerpt": "Abrir trecho", "ui.chapter.moveUp": "Subir", "ui.chapter.moveDown": "Descer",
  "ui.device.title": "Este dispositivo", "ui.device.limit": "Limite de dispositivos", "ui.device.replace": "Substituir dispositivo", "ui.device.authorize": "Autorizar dispositivo", "ui.license.active": "Licença ativa", "ui.license.expired": "Licença expirada", "ui.license.offline": "Período offline", "ui.license.checking": "Verificando licença", "ui.license.unavailable": "Não foi possível validar a licença.", "ui.license.reconnect": "Reconectar",
} as const;

export type InterfaceTranslationKey = keyof typeof INTERFACE_PT;
